'use strict';
const $=selector=>document.querySelector(selector),$$=selector=>[...document.querySelectorAll(selector)];
const root=document.documentElement,clamp=(n,a=0,b=1)=>Math.min(b,Math.max(a,n));
const motionPreference=matchMedia('(prefers-reduced-motion: reduce)');
let lowMotion=motionPreference.matches;
const menu=$('.menu-toggle'),mobile=$('#mobile-nav');function closeMenu(){mobile.hidden=true;menu.setAttribute('aria-expanded','false');menu.textContent='Menú +'}menu.addEventListener('click',()=>{const open=mobile.hidden;mobile.hidden=!open;menu.setAttribute('aria-expanded',String(open));menu.textContent=open?'Cerrar −':'Menú +'});mobile.querySelectorAll('a').forEach(a=>a.addEventListener('click',closeMenu));document.addEventListener('keydown',e=>{if(e.key==='Escape'&&!mobile.hidden){closeMenu();menu.focus()}});
const questions=[
{title:'¿Tu negocio depende principalmente de Instagram?',options:[['Sí, casi todo pasa ahí',0],['En parte',1],['No, tengo otros canales propios',2]],hint:'Pensá dónde te descubren y dónde terminan consultando.'},
{title:'¿Tenés una landing o web diseñada para convertir?',options:[['Sí, con un recorrido claro',2],['Tengo web, pero puede mejorar',1],['Todavía no',0]],hint:'Una página que muestra tu oferta y facilita una acción concreta.'},
{title:'¿Tu imagen representa el nivel real de tu negocio?',options:[['Sí, se siente coherente',2],['Solo en algunas piezas',1],['No, está por debajo de lo que ofrezco',0]],hint:'Considerá tu identidad, tus imágenes y tus mensajes.'},
{title:'¿Tus consultas llegan a un sistema o las respondés una por una?',options:[['Tengo un proceso organizado',2],['Mitad y mitad',1],['Las gestiono de forma manual',0]],hint:'Organizar no siempre significa automatizar: también implica un recorrido claro.'},
{title:'¿Usás automatización para captar o seguir consultas?',options:[['Sí, forma parte de mi proceso',2],['Tengo algunas cosas conectadas',1],['Todavía no',0]],hint:'Por ejemplo, respuestas iniciales, registro de consultas o seguimiento.'},
{title:'¿Existe un recorrido claro desde contenido, consulta y compra?',options:[['Sí, las etapas están conectadas',2],['En parte',1],['No, cada parte funciona por su lado',0]],hint:'Pensá qué pasa después de que alguien se interesa por tu marca.'}
];
const answers=Array(questions.length).fill(null);let current=0,completed=false;
const container=$('#question-container'),result=$('#quiz-result'),next=$('#quiz-next'),back=$('#quiz-back');
function paintQuestion(){completed=false;result.hidden=true;container.hidden=false;$('.quiz-nav').hidden=false;$('#question-step').textContent=String(current+1).padStart(2,'0')+' / 06';$('.quiz-progress i').style.width=(current/6*100)+'%';container.replaceChildren();const h=document.createElement('h3');h.id='question-title';h.tabIndex=-1;h.textContent=questions[current].title;const group=document.createElement('div');group.className='quiz-options';group.setAttribute('role','group');group.setAttribute('aria-labelledby','question-title');questions[current].options.forEach(([label,value],i)=>{const b=document.createElement('button');b.type='button';b.textContent=label;b.setAttribute('aria-pressed',String(answers[current]===value));const dot=document.createElement('span');dot.setAttribute('aria-hidden','true');b.append(dot);b.addEventListener('click',()=>{answers[current]=value;group.querySelectorAll('button').forEach((o,j)=>o.setAttribute('aria-pressed',String(j===i)));next.disabled=false;$('#score-label').textContent=answers.filter(v=>v!==null).length+' de 6 respuestas completas.'});group.append(b)});const hint=document.createElement('p');hint.className='question-hint';hint.textContent=questions[current].hint;container.append(h,group,hint);back.disabled=current===0;next.disabled=answers[current]===null;next.textContent=current===5?'Ver mi resultado ↗':'Siguiente →'}
function showResult(){if(answers.some(a=>a===null))return;completed=true;const raw=answers.reduce((a,b)=>a+b,0),pct=Math.round(raw/12*100);$('#score-num').textContent=pct+'%';$('#score-bar').style.width=pct+'%';$('#score-label').textContent='Lectura orientativa basada en tus seis respuestas.';$('#question-step').textContent='TU PRÓXIMO PASO';$('.quiz-progress i').style.width='100%';container.hidden=true;$('.quiz-nav').hidden=true;result.hidden=false;
 const values=raw<=5?{title:'Una base que te represente.',copy:'Tu prioridad está en ordenar cómo se presenta tu marca y construir un punto propio de consulta. Podemos trabajar esta base dentro de START Integral.',plan:'plan-escala',label:'Conocer START Integral',priorities:['Alinear imagen y propuesta de valor.','Tener una landing con una acción clara.','Conectar tus canales esenciales.']}:raw<=9?{title:'Conectar lo que ya tenés.',copy:'Ya hay piezas construidas. El próximo paso está en unirlas en un recorrido: desde el contenido hasta la consulta y el seguimiento.',plan:'plan-escala',label:'Conocer START Integral',priorities:['Detectar dónde se corta el recorrido.','Ordenar consultas y seguimiento.','Automatizar lo que hoy se repite.']}:{title:'Afinar una estructura que ya existe.',copy:'Tus respuestas muestran una base sólida. Conviene revisar la experiencia y los puntos de fricción antes de ampliar el sistema.',plan:'plan-escala',label:'Explorar un alcance a medida',priorities:['Revisar el recorrido desde el celular.','Medir dónde se pierde el interés.','Priorizar mejoras con un objetivo claro.']};
 const e=document.createElement('span');e.className='eyebrow';e.textContent='DIAGNÓSTICO DE MARCA';const h=document.createElement('h3');h.textContent=values.title;const p=document.createElement('p');p.textContent=values.copy;const ul=document.createElement('ul');values.priorities.forEach(t=>{const li=document.createElement('li');li.textContent=t;ul.append(li)});const a=document.createElement('a');a.className='button pink';a.href='#'+values.plan;a.textContent=values.label+' ↗';a.addEventListener('click',()=>{$$('.plan').forEach(p=>p.classList.remove('recommended'));document.getElementById(values.plan).classList.add('recommended')});result.replaceChildren(e,h,p,ul,a);h.tabIndex=-1;h.focus({preventScroll:true});$('.quiz-panel').scrollIntoView({behavior:lowMotion?'auto':'smooth',block:'start'});}
next.addEventListener('click',()=>{if(answers[current]===null)return;if(current===5)showResult();else{current++;paintQuestion();$('#question-title').focus({preventScroll:true});if($('.quiz-panel').getBoundingClientRect().top<85)$('.quiz-panel').scrollIntoView({behavior:lowMotion?'auto':'smooth',block:'start'})}});back.addEventListener('click',()=>{if(current>0){current--;paintQuestion();$('#question-title').focus({preventScroll:true});if($('.quiz-panel').getBoundingClientRect().top<85)$('.quiz-panel').scrollIntoView({behavior:lowMotion?'auto':'smooth',block:'start'})}});$('#quiz-reset').addEventListener('click',()=>{answers.fill(null);current=0;$('#score-num').textContent='—';$('#score-bar').style.width='0%';$('#score-label').textContent='Completá el diagnóstico para ver tu resultado.';paintQuestion();$('#question-title').focus({preventScroll:true});if($('.quiz-panel').getBoundingClientRect().top<85)$('.quiz-panel').scrollIntoView({behavior:lowMotion?'auto':'smooth',block:'start'})});paintQuestion();
