'use strict';
const $=s=>document.querySelector(s), root=document.documentElement;
const clamp=(v,a=0,b=1)=>Math.max(a,Math.min(b,v));
const reduced=matchMedia('(prefers-reduced-motion: reduce)');
let paused=reduced.matches,queued=false;
const sections=['inicio','humo','corredor','escala','contacto'].map(id=>document.getElementById(id));
const cards=[...document.querySelectorAll('.depthCard')];
const video=$('#heroVideo'),motion=$('#motionToggle');
const levelData=[['01','PRESENCIA','Existís digitalmente.','La presencia es el punto de partida. El objetivo es convertirla en una estructura con dirección.'],['02','IDENTIDAD','Empezás a ser reconocible.','Una identidad consistente hace que tu marca deje de sentirse improvisada.'],['03','POSICIONAMIENTO','Entienden por qué elegirte.','Ordenamos percepción, mensaje y diferencial para comunicar tu valor.'],['04','SISTEMA','Todo empieza a conectarse.','Web, contenido y captación dejan de funcionar como piezas aisladas.'],['05','AUTOMATIZACIÓN','El sistema trabaja con vos.','Ordenamos lo repetitivo para que puedas enfocarte en tu negocio.'],['06','ESCALA','Tu marca tiene estructura.','Más capacidad, más claridad y un recorrido preparado para crecer.']];
function sp(el){const r=el.getBoundingClientRect();return clamp(-r.top/Math.max(1,el.offsetHeight-innerHeight))}
function update(){queued=false;let [hp,sm,cp,sc,fp]=sections.map(sp);for(const [name,val] of Object.entries({hero:hp,smoke:sm,corr:cp,scale:sc,final:fp}))root.style.setProperty('--'+name,val);$('#header').classList.toggle('on',scrollY>40);$('#progress').style.transform=`scaleX(${scrollY/Math.max(1,root.scrollHeight-innerHeight)})`;
 root.style.setProperty('--noise-opacity',clamp(1-(sm-.3)*5));root.style.setProperty('--truth-opacity',clamp((sm-.43)*4));
 root.style.setProperty('--gallery-intro',clamp(1-cp*9));root.style.setProperty('--gallery-end',clamp((cp-.88)*10));$('.galleryEnd').classList.toggle('active',cp>.94);
 let active=Math.max(0,Math.min(5,Math.round(cp*8-1.4)));$('#galleryCount').textContent=cp<.09?'00':String(active+1).padStart(2,'0');$('#galleryLabel').textContent=cp<.09?'EL UNIVERSO START BRAND':cards[active].querySelector('figcaption span').textContent;
 cards.forEach((el,i)=>{const t=cp*8-1.4-i;let alpha=clamp((t+1.7)*1.3)*clamp((1.0-t)*2.7)*(1-clamp((cp-.87)*15));const side=i%2?1:-1;let x=side*(innerWidth<600?110:340)*Math.min(1,Math.abs(t)*.8),z=Math.min(850,t*780);if(paused){alpha=Math.abs(t)<.65?1:0;x=0;z=0}el.style.opacity=alpha;el.style.transform=`translate(-50%,-50%) translate3d(${x}px,${paused?0:Math.abs(t)*25}px,${z}px) rotateY(${paused?0:-side*Math.min(18,Math.abs(t)*13)}deg)`;el.style.zIndex=String(20-i);el.setAttribute('aria-hidden',alpha<.15?'true':'false')});
 const idx=Math.min(5,Math.floor(sc*6)),d=levelData[idx];$('#levelNum').textContent=d[0];$('#levelLabel').textContent=d[1];$('#scaleH').textContent=d[2];$('#scaleP').textContent=d[3];document.querySelectorAll('.node').forEach((n,i)=>n.classList.toggle('on',i<=idx));$('#pathGlow').style.strokeDashoffset=1-sc;
}
function schedule(){if(!queued){queued=true;requestAnimationFrame(update)}}
addEventListener('scroll',schedule,{passive:true});addEventListener('resize',schedule);update();
function setMotion(){document.body.classList.toggle('motionOff',paused);motion.setAttribute('aria-pressed',String(paused));motion.textContent=paused?'Activar movimiento':'Pausar movimiento';if(paused)video.pause();else if(sections[0].getBoundingClientRect().bottom>0)video.play().catch(()=>{});update()}
motion.addEventListener('click',()=>{paused=!paused;setMotion()});setMotion();
const videoObserver=new IntersectionObserver(entries=>{if(entries[0].isIntersecting&&!paused)video.play().catch(()=>{});else video.pause()});videoObserver.observe(sections[0]);
document.addEventListener('visibilitychange',()=>{if(document.hidden)video.pause();else if(!paused&&sections[0].getBoundingClientRect().bottom>0)video.play().catch(()=>{})});
const io=new IntersectionObserver(es=>es.forEach(e=>{if(e.isIntersecting){e.target.classList.add('in');io.unobserve(e.target)}}),{threshold:.1});document.querySelectorAll('.reveal').forEach(el=>io.observe(el));
const menu=$('.menuToggle'),mobileNav=$('#mobileNav');function closeMenu(){mobileNav.hidden=true;menu.setAttribute('aria-expanded','false');menu.textContent='Menú +'}menu.addEventListener('click',()=>{let open=mobileNav.hidden;mobileNav.hidden=!open;menu.setAttribute('aria-expanded',String(open));menu.textContent=open?'Cerrar −':'Menú +'});mobileNav.querySelectorAll('a').forEach(a=>a.addEventListener('click',closeMenu));addEventListener('keydown',e=>{if(e.key==='Escape'){closeMenu();menu.focus()}});
// diagnostic
const answers=new Array(6).fill(null);const scoreNum=document.getElementById('scoreNum'),gbar=document.getElementById('gbar'),glabel=document.getElementById('glabel'),result=document.getElementById('result');
document.querySelectorAll('.question').forEach(q=>q.querySelectorAll('.opt').forEach(btn=>btn.addEventListener('click',()=>{q.querySelectorAll('.opt').forEach(b=>b.classList.remove('sel'));btn.classList.add('sel');answers[+q.dataset.q]=+btn.dataset.v;const done=answers.filter(v=>v!==null).length;const raw=answers.reduce((a,v)=>a+(v??0),0);const pct=Math.round(raw/12*100);scoreNum.textContent=String(pct).padStart(2,'0');gbar.style.width=pct+'%';glabel.textContent=`${done}/6 señales leídas · ${pct}% de infraestructura`;if(done===6){let level,title,text;if(pct<30){level='LEVEL 01';title='Presencia';text='Tu negocio ya existe. El próximo salto está en ordenar identidad, mensaje y un punto propio de conversión.'}else if(pct<55){level='LEVEL 02';title='Posicionamiento';text='Ya hay base. Ahora conviene conectar percepción, landing y un recorrido comercial claro.'}else if(pct<80){level='LEVEL 03';title='Sistema';text='Tenés varias piezas resueltas. El siguiente salto está en conectarlas y automatizar lo repetitivo.'}else{level='LEVEL 04';title='Escala';text='Tu marca ya tiene estructura. El foco pasa a optimizar, medir y ampliar capacidad sin perder coherencia.'}document.getElementById('rlevel').textContent=level;document.getElementById('rtitle').textContent=title;document.getElementById('rtext').textContent=text;result.classList.add('show')}})));
const controls=document.createElement('div');controls.className='quizControls';controls.innerHTML='<button type="button" id="resetQuiz">Volver a empezar</button><span>Sin registro · tus respuestas quedan en esta página</span>';$('#quiz').after(controls);
const options=[...document.querySelectorAll('.opt')];options.forEach(b=>{b.setAttribute('aria-pressed','false');b.addEventListener('click',()=>{b.closest('.question').querySelectorAll('.opt').forEach(o=>o.setAttribute('aria-pressed',String(o===b)))})});
$('#resetQuiz').addEventListener('click',()=>{answers.fill(null);options.forEach(b=>{b.classList.remove('sel');b.setAttribute('aria-pressed','false')});scoreNum.textContent='00';gbar.style.width='0%';glabel.textContent='Respondé las 6 preguntas para ver tu nivel.';result.classList.remove('show');options[0].focus()});
