'use strict';
(()=>{
const section=document.querySelector('.value-story'),pin=section.querySelector('.value-pin'),chapters=[...section.querySelectorAll('.value-chapters article')],backgrounds=[...section.querySelectorAll('.value-backgrounds > *')],buttons=[...section.querySelectorAll('.value-pagination button')];let pending=false;
function render(){pending=false;const p=clamp(-section.getBoundingClientRect().top/Math.max(1,section.offsetHeight-innerHeight));const position=p*3;const active=Math.round(position);chapters.forEach((chapter,i)=>{const distance=position-i;const opacity=clamp(1-Math.max(0,Math.abs(distance)-.25)/.65);chapter.style.setProperty('--opacity',lowMotion?1:opacity);chapter.style.setProperty('--offset',(lowMotion?0:distance*-65)+'px');chapter.classList.toggle('is-active',lowMotion||i===active);chapter.inert=!lowMotion&&i!==active;chapter.setAttribute('aria-hidden',String(!lowMotion&&i!==active));backgrounds[i].style.setProperty('--opacity',clamp(1-Math.abs(distance)));backgrounds[i].style.setProperty('--scale',1.04+p*.08);buttons[i].setAttribute('aria-current',String(i===active))});}
function schedule(){if(!pending){pending=true;requestAnimationFrame(render)}}
buttons.forEach((button,i)=>button.addEventListener('click',()=>scrollTo({top:scrollY+section.getBoundingClientRect().top+(section.offsetHeight-innerHeight)*i/3,behavior:lowMotion?'auto':'smooth'})));
addEventListener('scroll',schedule,{passive:true});addEventListener('resize',schedule);document.querySelector('#motion-toggle').addEventListener('click',schedule);motionPreference.addEventListener('change',schedule);render();
})();
// Animate the supplied campaign clips only while they are in view.
(()=>{const videos=[...document.querySelectorAll('.abril-collection video, #vision, .immersive-case video')];const visible=new Set();const sync=()=>videos.forEach(v=>{if(visible.has(v)&&!lowMotion&&!document.hidden)v.play().catch(()=>{});else v.pause()});const observer=new IntersectionObserver(entries=>{entries.forEach(e=>{if(e.isIntersecting&&e.intersectionRatio>=.3)visible.add(e.target);else visible.delete(e.target)});sync()},{threshold:[0,.3]});videos.forEach(v=>observer.observe(v));document.addEventListener('visibilitychange',sync);motionPreference.addEventListener('change',sync);document.querySelector('#motion-toggle').addEventListener('click',sync)})();
