'use strict';
const demoCatalog={
moda:{name:'NOIR',category:'MODA EDITORIAL',kicker:'OBJETOS CON CARÁCTER / COLECCIÓN 01',title:'El detalle<br>lo cambia <em>todo.</em>',copy:'Piezas que no necesitan decir demasiado. Una colección para quienes eligen con intención.',image:'fashion-hd.png',alt:'Cartera negra de diseño en una composición editorial',cta:'Descubrir la colección',subtitle:'El deseo también se diseña.',description:'Fotografía protagonista, dirección editorial y un recorrido que lleva del deseo al producto.',section:'Menos piezas.<br>Más personalidad.',detail:'Una identidad propia se construye en cada decisión: la forma, la textura y la manera de mostrar lo que hacés.',features:['Diseño con intención','El detalle como protagonista','Una colección, un universo'],end:'Elegí tu próxima pieza.'},
belleza:{name:'RITUAL',category:'BEAUTY STUDIO',kicker:'EL CUIDADO TAMBIÉN ES UNA FORMA DE ARTE',title:'Tu tiempo.<br>Tu <em>ritual.</em>',copy:'Un espacio para detenerte. Un servicio donde la técnica y los pequeños detalles hacen la diferencia.',image:'beauty-hd.png',alt:'Detalle de manicura profesional',cta:'Conocer la experiencia',subtitle:'El cuidado se percibe antes de llegar.',description:'Una composición cálida, detalle profesional y servicios claros para acercar la próxima consulta.',section:'No es solo<br>una cita.',detail:'Es dedicarte un momento. Conocé las opciones, el proceso y los cuidados antes de elegir tu próxima experiencia.',features:['Una atención personal','Servicios explicados con claridad','Un momento para vos'],end:'Hacé espacio para vos.'},
bienestar:{name:'VOLVER',category:'BIENESTAR INMERSIVO',kicker:'UN ESPACIO PARA REENCONTRARTE',title:'Bajá el ruido.<br><em>Volvé a vos.</em>',copy:'Conectá con una pausa, un hábito y una nueva forma de estar presente. Tu próximo comienzo puede ser simple.',image:'wellness.png',alt:'Retrato en un entorno natural con agua y vegetación',cta:'Explorar el recorrido',subtitle:'Una web que invita a quedarse.',description:'Fotografía envolvente, una narrativa serena y un recorrido que acerca la propuesta sin saturar.',section:'Un paso pequeño.<br>Un lugar propio.',detail:'Una propuesta para descubrir a tu ritmo. Con contenido ordenado y una experiencia que acompaña desde el primer contacto.',features:['Descubrí la propuesta','Elegí tu recorrido','Encontrá tu espacio'],end:'Tu próximo comienzo.'},
personal:{name:'ABRIL',category:'MARCA PERSONAL',kicker:'IMAGEN / MODA / COMUNICACIÓN',title:'Una mirada.<br>Muchas <em>versiones.</em>',copy:'Televisión, editoriales y colaboraciones. Un lugar donde la imagen se convierte en una historia propia.',image:'abril-editorial.png',alt:'Abril Duhalde en una editorial de moda',cta:'Explorar el universo',subtitle:'Una persona. Un universo reconocible.',description:'Un portfolio con personalidad que reúne imagen, contenido y oportunidades de colaboración.',section:'Más allá<br>del feed.',detail:'Una selección editorial para reunir tus proyectos y presentar tu perfil con una voz propia. Concepto de landing inspirado en el material de Abril.',features:['Editoriales y campañas','Contenido y comunicación','Propuestas de colaboración'],end:'Hagamos algo memorable.'}
};
function demoHero(key){const d=demoCatalog[key];return `<div class="demo-document theme-${key}"><div class="demo-nav"><b>${d.name}</b><span>UNIVERSO &nbsp; / &nbsp; PROPUESTA</span><a href="#demo-details">Explorar ↗</a></div><section class="demo-hero"><div class="demo-art"><img src="assets/${d.image}" alt="${d.alt}"></div><div class="demo-hero-copy"><span>${d.kicker}</span><h2>${d.title}</h2><p>${d.copy}</p><a class="demo-action" href="#demo-details">${d.cta} ↗</a></div><div class="demo-edition">ESTUDIO START BRAND — PROPUESTA CONCEPTUAL</div></section></div>`}
function fullDemo(key){const d=demoCatalog[key];return `${demoHero(key)}<section id="demo-details" class="demo-details theme-${key}"><span class="demo-mini-label">EL UNIVERSO / ${d.name}</span><div class="demo-details-grid"><h2>${d.section}</h2><div><p>${d.detail}</p><a class="demo-action" href="#demo-contact">Conocer el siguiente paso ↗</a></div></div><div class="demo-feature-grid">${d.features.map((s,i)=>`<article><span>0${i+1}</span><h3>${s}</h3></article>`).join('')}</div></section><section id="demo-contact" class="demo-contact theme-${key}"><span class="demo-mini-label">UNA PROPUESTA DE START BRAND</span><h2>${d.end}</h2><p>Esto es una demostración de diseño. No se procesan compras, reservas ni consultas para esta marca desde aquí.</p><a class="demo-action" href="index.html#diagnostico" target="_top">Quiero una landing para mi marca ↗</a></section><footer class="demo-footer">${d.name} / CONCEPTO VISUAL &nbsp;·&nbsp; START BRAND</footer>`}
const standalone=document.querySelector('#standalone-demo');
if(standalone){const requested=new URLSearchParams(location.search).get('theme');const selected=Object.hasOwn(demoCatalog,requested)?requested:'moda';standalone.innerHTML=fullDemo(selected);document.title=demoCatalog[selected].name+' — Demo / START BRAND';}

const runway=document.querySelector('#runway-track');
if(runway){
 const demoDialog=document.querySelector('#demo-dialog'),frame=document.querySelector('#demo-frame');let origin=null;
 runway.innerHTML=Object.entries(demoCatalog).map(([key,d],i)=>`<article class="runway-card" data-theme="${key}"><div class="runway-browser"><div class="browser-chrome"><span class="browser-dots">● ● ●</span><span>${d.name} / ${d.category}</span><span>START BRAND</span></div><div class="runway-preview" aria-hidden="true" inert><div class="runway-preview-inner">${demoHero(key)}</div></div></div><div class="runway-meta"><div><h3>${d.subtitle}</h3><span>0${i+1} / ${d.category}</span></div><button data-open-demo="${key}">Abrir landing ↗</button></div></article>`).join('');
 function sizePreviews(){document.querySelectorAll('.runway-preview').forEach(el=>el.firstElementChild.style.transform='scale('+el.clientWidth/1000+')');}
 new ResizeObserver(sizePreviews).observe(runway);sizePreviews();
 document.querySelectorAll('[data-open-demo]').forEach(button=>button.addEventListener('click',()=>{origin=button;const selected=button.dataset.openDemo;frame.src='demo.html?v=8&theme='+selected;frame.title='Demo de landing: '+demoCatalog[selected].category;document.querySelector('#demo-dialog-label').textContent=demoCatalog[selected].name+' / DEMO INTERACTIVA';demoDialog.showModal();document.body.classList.add('modal-open')}));
 document.querySelector('#close-demo').addEventListener('click',()=>demoDialog.close());demoDialog.addEventListener('close',()=>{document.body.classList.remove('modal-open');frame.src='about:blank';origin?.focus({preventScroll:true})});
 const proofDialog=document.querySelector('#proof-dialog'),proofImage=document.querySelector('#proof-image');let proofOrigin=null;
 document.querySelectorAll('[data-proof]').forEach(button=>button.addEventListener('click',()=>{proofOrigin=button;proofImage.src='assets/'+button.dataset.proof;proofImage.alt=button.dataset.proofTitle;document.querySelector('#proof-title').textContent=button.dataset.proofTitle;proofDialog.showModal();document.body.classList.add('modal-open')}));
 document.querySelector('#close-proof').addEventListener('click',()=>proofDialog.close());proofDialog.addEventListener('close',()=>{document.body.classList.remove('modal-open');proofOrigin?.focus({preventScroll:true})});
}
