let CSRF="",DATA={};const q=s=>document.querySelector(s),esc=v=>String(v??"").replace(/[&<>'"]/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;","'":"&#39;",'"':"&quot;"}[c]));
async function api(path,opts={}){const h=new Headers(opts.headers||{});if(opts.body)h.set("content-type","application/json");if(opts.method&&opts.method!=="GET"&&CSRF)h.set("x-csrf-token",CSRF);const r=await fetch(path,{...opts,headers:h,credentials:"same-origin"});let d={};try{d=await r.json()}catch(_){}if(r.status===401){location.href="/campus/login.html";throw new Error("AUTH")}if(!r.ok)throw new Error(d.message||d.error||"Error");return d}
const money=(c,cur="ARS")=>new Intl.NumberFormat("es-AR",{style:"currency",currency:cur,maximumFractionDigits:0}).format((c||0)/100);
const date=v=>v?new Date(Number(v)).toLocaleString("es-AR"):"—";
async function load(){const s=await api("/api/session");if(s.user.role!=="admin"){location.href="/campus/";return}CSRF=s.csrf;DATA=await api("/api/admin/dashboard");render()}
function render(){const p=DATA.product||{};q("#product-title").value=p.title||"START BRAND · Programa";q("#product-price").value=Math.round((p.price_cents||0)/100);q("#product-active").checked=!!p.active;q("#stat-users").textContent=(DATA.users||[]).filter(x=>x.role==="student").length;q("#stat-sales").textContent=(DATA.purchases||[]).filter(x=>["approved","claimed"].includes(x.status)).length;q("#stat-mentor").textContent=(DATA.mentoring||[]).filter(x=>x.status==="pending").length;renderUsers();renderPurchases();renderMentoring();renderModules()}
function renderUsers(){q("#users-body").innerHTML=(DATA.users||[]).map(u=>'<tr><td><strong>'+esc(u.name)+'</strong>'+esc(u.email)+'</td><td>'+esc(u.role)+'</td><td><span class="pill '+esc(u.status)+'">'+esc(u.status)+'</span></td><td>'+date(u.created_at)+'</td><td><div class="row-actions">'+(u.role==="admin"?"":'<button class="mini" data-toggle="'+esc(u.id)+'" data-status="'+(u.status==="active"?"suspended":"active")+'">'+(u.status==="active"?"Suspender":"Activar")+'</button><button class="mini" data-reset="'+esc(u.id)+'">Reset contraseña</button>')+'</div></td></tr>').join("");document.querySelectorAll("[data-toggle]").forEach(b=>b.onclick=()=>toggleUser(b.dataset.toggle,b.dataset.status));document.querySelectorAll("[data-reset]").forEach(b=>b.onclick=()=>resetUser(b.dataset.reset))}
function renderPurchases(){q("#purchases-body").innerHTML=(DATA.purchases||[]).map(p=>'<tr><td><strong>'+esc(p.name)+'</strong>'+esc(p.email)+'</td><td>'+money(p.amount_cents,p.currency)+'</td><td><span class="pill '+esc(p.status)+'">'+esc(p.status)+'</span></td><td>'+esc(p.mp_status||"—")+'</td><td>'+date(p.created_at)+'</td></tr>').join("")||'<tr><td colspan="5" class="muted">Todavía no hay compras.</td></tr>'}
function renderMentoring(){const box=q("#mentoring-list");box.innerHTML="";(DATA.mentoring||[]).forEach(m=>{const d=document.createElement("div");d.className="mentor-row";d.innerHTML='<div><strong>'+esc(m.name)+'</strong><div class="muted">'+esc(m.email)+' · '+esc(m.session_name)+' · '+esc(m.preferred_date)+' · '+esc(m.slot)+'</div><div class="muted">'+esc(m.notes||"")+'</div></div><label>Estado<select data-ms="'+esc(m.id)+'"><option value="pending">Pendiente</option><option value="confirmed">Confirmada</option><option value="completed">Realizada</option><option value="cancelled">Cancelada</option></select></label><label>Link Google Meet<input data-mm="'+esc(m.id)+'" placeholder="https://meet.google.com/..." value="'+esc(m.meet_url||"")+'"></label><button class="mini" data-save-mentor="'+esc(m.id)+'">Guardar</button>';box.appendChild(d);d.querySelector("[data-ms]").value=m.status});document.querySelectorAll("[data-save-mentor]").forEach(b=>b.onclick=()=>saveMentor(b.dataset.saveMentor))}
function renderModules(){const box=q("#modules-list");box.innerHTML="";(DATA.modules||[]).forEach(m=>{const d=document.createElement("div");d.className="module-row";d.innerHTML='<b>'+String(m.id).padStart(2,"0")+'</b><div><strong>'+esc(m.title)+'</strong></div><input data-video="'+m.id+'" placeholder="https://youtube.com/watch?v=..." value="'+esc(m.video_url||"")+'"><button class="mini" data-save-video="'+m.id+'">Guardar</button>';box.appendChild(d)});document.querySelectorAll("[data-save-video]").forEach(b=>b.onclick=()=>saveVideo(Number(b.dataset.saveVideo)))}
async function refresh(){DATA=await api("/api/admin/dashboard");render()}
q("#product-form").addEventListener("submit",async e=>{e.preventDefault();const s=q("#product-status");s.textContent="Guardando…";try{await api("/api/admin/product",{method:"POST",body:JSON.stringify({title:q("#product-title").value,price_ars:Number(q("#product-price").value),active:q("#product-active").checked})});s.textContent="✓ Venta actualizada";await refresh()}catch(err){s.textContent=err.message}})
q("#invite-form").addEventListener("submit",async e=>{e.preventDefault();const s=q("#invite-status");s.textContent="Creando…";try{const d=await api("/api/admin/invites",{method:"POST",body:JSON.stringify({name:q("#invite-name").value,email:q("#invite-email").value})});q("#invite-link").hidden=false;q("#invite-link").textContent=d.url;s.textContent="✓ Copiá este enlace y mandáselo al alumno.";await navigator.clipboard?.writeText(d.url)}catch(err){s.textContent=err.message}})
async function toggleUser(id,status){if(!confirm((status==="suspended"?"Suspender":"Activar")+" esta cuenta?"))return;await api("/api/admin/user-status",{method:"POST",body:JSON.stringify({user_id:id,status})});await refresh()}
async function resetUser(id){const d=await api("/api/admin/password-reset",{method:"POST",body:JSON.stringify({user_id:id})});q("#reset-link").hidden=false;q("#reset-link").textContent=d.url;await navigator.clipboard?.writeText(d.url)}
async function saveMentor(id){const status=q('[data-ms="'+id+'"]').value,meet_url=q('[data-mm="'+id+'"]').value;await api("/api/admin/mentor-update",{method:"POST",body:JSON.stringify({id,status,meet_url})});await refresh()}
async function saveVideo(module_id){const video_url=q('[data-video="'+module_id+'"]').value;await api("/api/admin/module-video",{method:"POST",body:JSON.stringify({module_id,video_url})});await refresh()}
q("#logout").onclick=async()=>{try{await api("/api/logout",{method:"POST",body:"{}"})}catch(_){}location.href="/campus/login.html"};
load().catch(err=>{console.error(err)});